version: "3.8"
services:
  mysqldb:
    image:  mysql:latest
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    ports:
      - 3306:3306

  springboot-mysql:
    build: .
    container_name: springboot-mysql
    ports:
      - 8082:8080
    links:
      - mysqldb